# Stubs for docker.types.base (Python 3)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from typing import Any

class DictType(dict):
    def __init__(self, init: Any) -> None: ...
