# Stubs for docker.types.networks (Python 3)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from ..utils import normalize_links, version_lt
from typing import Any, Optional

class EndpointConfig(dict):
    def __init__(self, version: Any, aliases: Optional[Any] = ..., links: Optional[Any] = ..., ipv4_address: Optional[Any] = ..., ipv6_address: Optional[Any] = ..., link_local_ips: Optional[Any] = ...) -> None: ...

class NetworkingConfig(dict):
    def __init__(self, endpoints_config: Optional[Any] = ...) -> None: ...

class IPAMConfig(dict):
    def __init__(self, driver: str = ..., pool_configs: Optional[Any] = ..., options: Optional[Any] = ...) -> None: ...

class IPAMPool(dict):
    def __init__(self, subnet: Optional[Any] = ..., iprange: Optional[Any] = ..., gateway: Optional[Any] = ..., aux_addresses: Optional[Any] = ...) -> None: ...
