# Stubs for docker.api.build (Python 3)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from typing import Any, Optional

log: Any

class BuildApiMixin:
    def build(self, path: Optional[Any] = ..., tag: Optional[Any] = ..., quiet: bool = ..., fileobj: Optional[Any] = ..., nocache: bool = ..., rm: bool = ..., timeout: Optional[Any] = ..., custom_context: bool = ..., encoding: Optional[Any] = ..., pull: bool = ..., forcerm: bool = ..., dockerfile: Optional[Any] = ..., container_limits: Optional[Any] = ..., decode: bool = ..., buildargs: Optional[Any] = ..., gzip: bool = ..., shmsize: Optional[Any] = ..., labels: Optional[Any] = ..., cache_from: Optional[Any] = ..., target: Optional[Any] = ..., network_mode: Optional[Any] = ..., squash: Optional[Any] = ..., extra_hosts: Optional[Any] = ..., platform: Optional[Any] = ..., isolation: Optional[Any] = ..., use_config_proxy: bool = ...): ...
    def prune_builds(self): ...

def process_dockerfile(dockerfile: Any, path: Any): ...
