# Stubs for docker.api.client (Python 3)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

import requests.exceptions
from ..constants import DEFAULT_DOCKER_API_VERSION, DEFAULT_NUM_POOLS, DEFAULT_NUM_POOLS_SSH, DEFAULT_TIMEOUT_SECONDS, DEFAULT_USER_AGENT, IS_WINDOWS_PLATFORM, MINIMUM_DOCKER_API_VERSION, STREAM_HEADER_SIZE_BYTES
from ..errors import DockerException, InvalidVersion, TLSParameterError, create_api_error_from_http_exception
from ..tls import TLSConfig
from ..transport import NpipeHTTPAdapter, SSHHTTPAdapter, SSLHTTPAdapter, UnixHTTPAdapter
from ..utils import check_resource, config, update_headers, utils
from ..utils.json_stream import json_stream
from ..utils.proxy import ProxyConfig
from ..utils.socket import consume_socket_output, demux_adaptor, frames_iter
from .build import BuildApiMixin
from .config import ConfigApiMixin
from .container import ContainerApiMixin
from .daemon import DaemonApiMixin
from .exec_api import ExecApiMixin
from .image import ImageApiMixin
from .network import NetworkApiMixin
from .plugin import PluginApiMixin
from .secret import SecretApiMixin
from .service import ServiceApiMixin
from .swarm import SwarmApiMixin
from .volume import VolumeApiMixin
from typing import Any, Optional

class APIClient(requests.Session, BuildApiMixin, ConfigApiMixin, ContainerApiMixin, DaemonApiMixin, ExecApiMixin, ImageApiMixin, NetworkApiMixin, PluginApiMixin, SecretApiMixin, ServiceApiMixin, SwarmApiMixin, VolumeApiMixin):
    __attrs__: Any = ...
    base_url: Any = ...
    timeout: Any = ...
    credstore_env: Any = ...
    def __init__(self, base_url: Optional[Any] = ..., version: Optional[Any] = ..., timeout: Any = ..., tls: bool = ..., user_agent: Any = ..., num_pools: Optional[Any] = ..., credstore_env: Optional[Any] = ...) -> None: ...
    def get_adapter(self, url: Any): ...
    @property
    def api_version(self): ...
    def reload_config(self, dockercfg_path: Optional[Any] = ...) -> None: ...
