# Stubs for docker.transport (Python 3)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from .npipeconn import NpipeHTTPAdapter
from .npipesocket import NpipeSocket
from .sshconn import SSHHTTPAdapter
from .ssladapter import SSLHTTPAdapter
from .unixconn import UnixHTTPAdapter
