# Stubs for docker.transport.basehttpadapter (Python 3)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

import requests.adapters

class BaseHTTPAdapter(requests.adapters.HTTPAdapter):
    def close(self) -> None: ...
