"""Typestubs for docker.constants."""

from typing import List, Tuple

DEFAULT_DOCKER_API_VERSION: str
MINIMUM_DOCKER_API_VERSION: str
DEFAULT_TIMEOUT_SECONDS: int
STREAM_HEADER_SIZE_BYTES: int
CONTAINER_LIMITS_KEYS: List[str]
INSECURE_REGISTRY_DEPRECATION_WARNING: str
IS_WINDOWS_PLATFORM: Tuple[bool]
WINDOWS_LONGPATH_PREFIX: str
DEFAULT_USER_AGENT: str
DEFAULT_NUM_POOLS: int
DEFAULT_NUM_POOLS_SSH: int
DEFAULT_DATA_CHUNK_SIZE: int
DEFAULT_SWARM_ADDR_POOL: List[str]
DEFAULT_SWARM_SUBNET_SIZE: int
