# Stubs for docker.credentials (Python 3)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from .constants import *
from .errors import CredentialsNotFound, StoreError
from .store import Store
