# Stubs for docker.credentials.constants (Python 3)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

PROGRAM_PREFIX: str
DEFAULT_LINUX_STORE: str
DEFAULT_OSX_STORE: str
DEFAULT_WIN32_STORE: str
