# Stubs for docker.credentials.utils (Python 3)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from typing import Any, Optional

def find_executable(executable: Any, path: Optional[Any] = ...): ...
def create_environment_dict(overrides: Any): ...
