# Stubs for docker.utils.config (Python 3)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from ..constants import IS_WINDOWS_PLATFORM
from typing import Any, Optional

DOCKER_CONFIG_FILENAME: Any
LEGACY_DOCKER_CONFIG_FILENAME: str
log: Any

def find_config_file(config_path: Optional[Any] = ...): ...
def config_path_from_environment(): ...
def home_dir(): ...
def load_general_config(config_path: Optional[Any] = ...): ...
